### ISSUE TITLE
gonna need vclear text, and our code

### ISSUE THREAD

**Issue by timm** [ai-se/hownot#10]
so it looks like the new and old paper are actually comparing instance based vs dt-based to generate the contrasts

many undocumented aspects, that the text should answer.
1. does it work for makefile config?
2. when you descend , you dividing at median (and do u cache the median's projected x value)?
3. when decision tree is built, does it use ediv on cluster name? does it use fayyadIrani to discretize the data?
4. when a test case arrives, does it use that cached x to find its "current" half? or does it use decision tree to find "current"?
5. how is "desired" found?
6. just checking: is proposed delta the set difference branches desired to current?
7. now if you are using FI (from question3), how to turn that delta into a change? i.e. which parts of the FI range do you use?
8. just checking: given a changed instance, do you assess it with the predictor (good) or throw it back into the decision tree (less than good)

**Comment by rahlk** [comment]
1. does it work for makefile config?
   No.
2. when you descend , you dividing at median (and do u cache the median's projected x value)?
   Not sure what this means 
3. when decision tree is built, does it use ediv on cluster name? does it use fayyadIrani to discretize the data?
   FI
4. when a test case arrives, does it use that cached x to find its "current" half? or does it use decision tree to find "current"?
   Dtree
5. how is "desired" found?
   a. score (better) alpha(0.5)*me
   b. same level
   c. midpoint dist
6. just checking: is proposed delta the set difference branches desired to current?
   Yes
7. now if you are using FI (from question3), how to turn that delta into a change? i.e. which parts of the FI range do you use?
   
   ``` python
   max(lo, min(hi, lo + rand() * abs(hi - lo))) 
   ```
8. just checking: given a changed instance, do you assess it with the predictor (good) or throw it back into the decision tree (less than good)
   predictor
