### ISSUE TITLE
Citation for HOW: Unpublished?

### ISSUE THREAD

**Issue by rahlk** [ai-se/hownot#16]

**Comment by timm** [comment]
wrute uo the ase submussion and use the submitted to conventoon, shown below

@inproceedings{me12c,
annote = {Available from http://menzies.us/pdf/12idea.pdf},
author = {Borges, R and Menzies, T},
booktitle = {Submitted to PROMISE'12, Lund, Sweden},
title = {{Learning to Change Projects}},
year = {2012}
}
