### ISSUE TITLE
Tree Learner Doesn't Fail

### ISSUE THREAD

**Issue by rahlk** [ai-se/hownot#3]
```
rank ,         name ,    med   ,  iqr 
----------------------------------------------------
   1 ,          ant ,    0.67  ,  0.40 (  -------------|--*           ), 0.29,  0.67,  0.69
   1 ,        jedit ,    0.68  ,  0.14 (               | --*          ), 0.66,  0.68,  0.79
   1 ,       lucene ,    0.72  ,  0.04 (               |   -*         ), 0.70,  0.72,  0.74
   1 ,          poi ,    0.72  ,  0.18 (               |----*         ), 0.64,  0.72,  0.82
   2 ,          ivy ,    0.85  ,  0.09 (               |          *   ), 0.85,  0.85,  0.94
```

**Comment by rahlk** [comment]
HOW's results:
![image](https://cloud.githubusercontent.com/assets/1433964/8394812/826a4a3a-1d17-11e5-8d42-f7bf0b8b9b04.png)

**Comment by timm** [comment]
I love grad students. huge graphics, no summary. i would have added a comment summarizes the results

:-) ant old = 71 new = 67
:-( ivy old = 75 new = 85
:-) jedit old = 76 new = 68
:-( lucence old = 66 new = 72
:-) poi old = 72 new =  72

 so some wins, some losses, no overall winner. but note that these
results are FAR more explainable that before :-) :-) :-) :-)
